stages:
  - test
  - name: deploy
    if: branch = master

language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
jobs:
  include:
    - stage: test
      install: yarn install --ignore-engines
    - stage: deploy
      install: yarn install --ignore-engines
      node_js: '12'
      # required for yarn not to fail when installing semantic-release
      # instead it is removed from the dependencies and added as global at the end
      script: yarn global add semantic-release && semantic-release || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
